services:

    sftp-server:
        container_name: sftp-server
        build: .
        environment:
            - AUTHORIZED_PUBLIC_KEYS=
            - HOST_KEY=
        volumes:
            - ./data-local/ssh-key.pub:/media/ssh/authorized_keys:ro
            - ./data-local/ssh-key:/media/ssh/host_key:ro
        ports:
            - "127.0.0.1:8022:22"
