version: "3.8"

services:

    sftp-server:
        container_name: sftp-server
        build: .
        environment:
            - AUTHORIZED_PUBLIC_KEYS=
            - |
                HOST_KEY=-----BEGIN OPENSSH PRIVATE KEY-----
                ...
                -----END OPENSSH PRIVATE KEY-----

        ports:
            - "8022:22"
